substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  #UART 1
  pin_tuya_rx: P10
  pin_tuya_tx: P11
  #bauds are usually 115200 and 9600
  tuya_baud: "9600"
  preset_name_1: 5m
  preset_name_2: 10m
  preset_name_3: 30m
  preset_name_4: 60m
  preset_name_5: 2h
  preset_name_6: 4h
  comment: Minoston Fan Timer MT10W
  devicename: "master-bathroom-fan"

esphome:
  name: ${devicename}
  comment: ${comment}
  project:
    name: Minoston.MT10W
    version: 1.0.0

web_server:
  auth:
    username: admin
    password: !secret web_server_password 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  passive_scan: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "master-bathroom-fan"
    password: !secret web_server_password
    ap_timeout: 3min

captive_portal:

time:
  - platform: sntp
    timezone: "US/Mountain"
    servers:
      - 192.168.20.1

ota:
  - platform: esphome
  - platform: web_server

api:
logger:

bk72xx:
  board: cb2s

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    mac_address:
      name: "MAC Address"

sensor:
- platform: template
  id: time_remaining
  name: ${devicename} Time Remaining
  icon: mdi:timer
  accuracy_decimals: 0
  filters:
    - timeout:
        timeout: 10s
        value: 0
  unit_of_measurement: s
  device_class: duration
  state_class: measurement
- platform: template
  id: expected_duration
  name: ${devicename} Expected Duration
  icon: mdi:timer
  accuracy_decimals: 0
  unit_of_measurement: s
  device_class: duration
  state_class: measurement

#TuyaMCU
uart:
  rx_pin: ${pin_tuya_rx}
  tx_pin: ${pin_tuya_tx}
  baud_rate: ${tuya_baud}
tuya:
  on_datapoint_update:
    - sensor_datapoint: 7 #Seconds remaining
      datapoint_type: int
      then:
        - lambda: |-
            id(time_remaining).publish_state(x);

switch:
- platform: "tuya"
  id: fan
  name: ${devicename} Timed
  icon: mdi:fan-clock
  switch_datapoint: 1
- platform: "tuya"
  id: fan_untimed
  icon: mdi:fan
  name: ${devicename} Untimed
  switch_datapoint: 111
- platform: template
  id: night_light
  name: ${devicename} Night Light
  entity_category : config
  lambda: |-
    if (id(night_light_enum).active_index().value() < 1){
      return true;
    } else {
      return false;
    }
  turn_on_action:
    - select.set_index:
        id: night_light_enum
        index: 0
  turn_off_action:
    - select.set_index:
        id: night_light_enum
        index: 1
- platform: template
  id: preset_led
  name: ${devicename} Preset LED
  entity_category : config
  lambda: |-
    if (id(timer_led_behavior_enum).active_index().value() < 1){
      return true;
    } else {
      return false;
    }
  turn_on_action:
    - select.set_index:
        id: timer_led_behavior_enum
        index: 0
  turn_off_action:
    - select.set_index:
        id: timer_led_behavior_enum
        index: 1
select:
- platform: "tuya"
  id: "night_light_enum"
  name: "Night Light"
  enum_datapoint: 109
  options:
    0: Enabled # Index 0
    1: Disabled # Index 1
  entity_category : config
  internal: true
- platform: "tuya"
  id: "timer_led_behavior_enum"
  name: "Timer LED Behavior"
  enum_datapoint: 110
  options:
    0: On After Blink # Index 0
    1: Off After Blink # Index 1
  entity_category : config
  internal: true
# Offers a select for the preset. Comment this out and the internal property of timer_preset_id if you want a numeric preset.
- platform: template
  id: "timer_preset"
  name: ${devicename} Timer Preset
  options: # Regular select templates start at index 0. The timer presets starts at 1.
    - "${preset_name_1} Preset" # Index 1
    - "${preset_name_2} Preset" # Index 2
    - "${preset_name_3} Preset" # Index 3
    - "${preset_name_4} Preset" # Index 4
    - "${preset_name_5} Preset" # Index 5
    - "${preset_name_6} Preset" # Index 6
  lambda: |-
    return id(timer_preset).at(id(timer_preset_id).state -1).value();
  set_action:
    - lambda: |-
        auto call = id(timer_preset_id).make_call();
        call.set_value(id(timer_preset).index_of(x).value()+1);
        call.perform();
number:
- platform: "tuya"
  id: "timer_preset_id"
  name: "Timer Preset ID"
  number_datapoint: 108
  min_value: 1
  max_value: 6
  step: 1
  mode: slider
  internal: true
  on_value:
    then:
      - lambda: id(set_expected_duration)->execute(x);
      - component.update: timer_preset
- platform: "tuya"
  id: led_brightness
  name: ${devicename} LED Brightness
  number_datapoint: 107
  min_value: 0
  max_value: 100
  step: 1
  entity_category : config
  mode: slider
- platform: "tuya"
  id: "timer_preset_${preset_name_1}"
  name: "${devicename} ${preset_name_1} Preset"
  number_datapoint: 101
  min_value: 5
  max_value: 1440
  step: 1
  unit_of_measurement: seconds
  entity_category : config
- platform: "tuya"
  id: "timer_preset_${preset_name_2}"
  name: "${devicename} ${preset_name_2} Preset"
  number_datapoint: 102
  min_value: 5
  max_value: 1440
  step: 1
  unit_of_measurement: seconds
  entity_category : config
- platform: "tuya"
  id: "timer_preset_${preset_name_3}"
  name: "${devicename} ${preset_name_3} Preset"
  number_datapoint: 103
  min_value: 5
  max_value: 1440
  step: 1
  unit_of_measurement: seconds
  entity_category : config
- platform: "tuya"
  id: "timer_preset_${preset_name_4}"
  name: "${devicename} ${preset_name_4} Preset"
  number_datapoint: 104
  min_value: 5
  max_value: 1440
  step: 1
  unit_of_measurement: seconds
  entity_category : config
- platform: "tuya"
  id: "timer_preset_${preset_name_5}"
  name: "${devicename} ${preset_name_5} Preset"
  number_datapoint: 105
  min_value: 5
  max_value: 1440
  step: 1
  unit_of_measurement: seconds
  entity_category : config
- platform: "tuya"
  id: "timer_preset_${preset_name_6}"
  name: "${devicename} ${preset_name_6} Preset"
  number_datapoint: 106
  min_value: 5
  max_value: 1440
  step: 1
  unit_of_measurement: seconds
  entity_category : config

script:
  - id: set_expected_duration
    mode: single
    parameters:
      x: float
    then:
      - lambda: |-
          switch ((int)x) {
            case 1:
              id(expected_duration).publish_state(id(timer_preset_${preset_name_1}).state);
              break;
            case 2:
              id(expected_duration).publish_state(id(timer_preset_${preset_name_2}).state);
              break;
            case 3:
              id(expected_duration).publish_state(id(timer_preset_${preset_name_3}).state);
              break;
            case 4:
              id(expected_duration).publish_state(id(timer_preset_${preset_name_4}).state);
              break;
            case 5:
              id(expected_duration).publish_state(id(timer_preset_${preset_name_5}).state);
              break;
            case 6:
              id(expected_duration).publish_state(id(timer_preset_${preset_name_6}).state);
              break;
          }