substitutions:
  firmware_version: "0.0.0"
  name: olimex-bluetooth-proxy-d10148
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/olimex/olimex-esp32-poe-iso.yaml@main
  ota_updates: !include includes/ota-updates.yaml
ota:
  - platform: esphome
  - platform: http_request

esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: lilmansplace.olimex_bluetooth_proxy_d10148
    version: ${firmware_version}
